### ISSUE TITLE
Error in documentation: /devtools/teststudiodev/features/recorder/verifications/image-verification

### ISSUE THREAD

**Issue by Syntribos** [telerik/teststudio#14]
Current text:

> By default, Verify Entire Image is checked and the Threshold is set to 90%.

> We recommend keeping the Threshold around 90%. A setting of 100% equals an exact match and the verification will fail, if it is off by a single pixel.

This is the opposite of how it works (at least for WPF testing). The default appears to be 1%, and higher tolerance means the verification is more forgiving, not less (i.e. tolerance of 0 is pixel perfect, 100 would pass with any image)

**Comment by tsvetkoe** [comment]
Hi Syntribos, 
Thanks for noting this. It will be fixed as soon as possible.
